# Generated by Django 2.0.6 on 2018-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwtmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trinkets',
            name='coords',
            field=models.CharField(default=(54.3, 52.4), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trinkets',
            name='picture',
            field=models.ImageField(max_length=50, upload_to='imgs'),
        ),
    ]
